data_conf:
  data_path: data/mfcc/libri_mix_0.3
  dump_path: dump/libri_mix_0.3
  audio_path: data/libri_mix_0.3
  #data_path: data/mfcc/wsj_mix_0.3
  #dump_path: dump/wsj_mix_0.3
  #audio_path: data/wsj_mix_0.3
  sr: 16000
  win_ms: 25
  hop_ms: 10
  #use_rate: 0.005
  use_rate: 10
  train_name: train-clean-100
  val_name: dev-clean
  test_name: test-clean
  #train_name: si_tr_s
  #val_name: si_dt_05
  #test_name: si_et_05

fea_conf:
  fea_name: mfcc
  n_fea: 16

train_conf:
  epochs: 50
  lr: 0.0001
  early_stop: True
  num_early: 5
  batch_size: 32
  input_size: 64
  n_class: 3
  zero_class: True #True - train with 0 class / False - train without '0'class
  only_test: False
  test_folder: '0902_branch_unet_3_small_layer4_nodrop'
  #test_folder: '0902_unet'

model_conf:
  #model_name: proposed_model
  #model_name: unet
  #model_name: cnn
  #model_name: asymmetric_unet
  #model_name: apply_multi_window
  model_name: apply_asymetric_reducefilter

encoder_conf:
  n_layers: 7
  D_layers: [32,64,128,256,128,64,32]
  kernel_size: [3,3,3,3,3,3,3]
#  input_size: 64